DECLARE
  l_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_cnt FROM dba_users t WHERE t.username='LIB_MANAGER';
  IF l_cnt=1 THEN 
    EXECUTE IMMEDIATE 'DROP USER lib_manager CASCADE';
  END IF;
END;

CREATE USER lib_manager 
  IDENTIFIED BY 123
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON users
;

GRANT CREATE SESSION TO lib_manager;
GRANT CREATE TABLE TO lib_manager;
GRANT CREATE VIEW TO lib_manager;
GRANT CREATE SEQUENCE TO lib_manager;
GRANT CREATE PROCEDURE TO lib_manager;
GRANT CREATE TYPE TO lib_manager;
GRANT CREATE TRIGGER TO lib_manager;


